webtalk_init -webtalk_dir /home/pengmiao/vivado/599_project/my_lstm_try6_final/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_network_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May  9 18:08:46 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f2a67983-3a28-478f-8c29-a04b189b62d3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7c8d69c47db34628bbb988fe04dd87cf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "292" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1000.049 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "134.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "19881 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.92_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "134964_KB" -context "xsim\\usage"
webtalk_transmit -clientid 345968754 -regid "174127931_174127932_210706859_805" -xml /home/pengmiao/vivado/599_project/my_lstm_try6_final/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_network_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/pengmiao/vivado/599_project/my_lstm_try6_final/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_network_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/pengmiao/vivado/599_project/my_lstm_try6_final/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_network_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
